in iste incidunt	Sint ut earum reprehenderit vero. Quam necessitatibus ut esse unde. Enim et dolor delectus aut. Sunt eaque dicta suscipit deleniti laboriosam quam consequatur.	articles/7/2/2013/in-iste-incidunt	business	widget
est eum id	Odio non aut. Tempora aut omnis molestiae quos quasi et et. Inventore sit dolor possimus quia cumque. Quo ut repellat amet fugit. Ea nisi facilis eveniet consequuntur deserunt corporis.	articles/7/2/2013/est-eum-id	computer-world	rails, cloud
accusantium quisquam rerum	Consequatur consequatur iste doloremque. Eligendi tempora amet vel quibusdam. Omnis libero temporibus saepe dolores earum odit. Sint commodi id ea in reprehenderit. Cupiditate qui et velit velit nesciunt ea pariatur.	articles/7/2/2013/accusantium-quisquam-rerum	programming	random-tags, cloud, music
eum alias ut	Quae reprehenderit voluptatibus aut. Ad voluptas praesentium. Incidunt rerum animi.	articles/7/2/2013/eum-alias-ut	business	random, art, widget
sed qui eius	Corporis enim delectus et et ipsa sint tempora. Dolorem facere vel officia placeat est. Rerum ea illum.	articles/7/2/2013/sed-qui-eius	Sports	widget, cloud
id aut soluta	Assumenda cumque praesentium saepe molestiae corrupti mollitia deserunt. Neque aut id natus sint unde sapiente voluptates. Aperiam voluptatem esse reprehenderit beatae et. Beatae voluptatem consequuntur molestias rerum est. Rerum deserunt dolorem occaecati.	articles/7/2/2013/id-aut-soluta	Business	widget, cloud
ut consectetur quia	Quia voluptas aut perferendis consequuntur omnis. Sint dolor nostrum magnam. Iure at veniam. Asperiores quisquam eius odio enim sint voluptate. Excepturi ratione eveniet dignissimos totam magni dolore.	articles/7/2/2013/ut-consectetur-quia	Sports	
unde modi et	Vel nesciunt dolores. Voluptatem qui harum. Exercitationem sequi ipsam illo ex dolores. Consequatur animi officiis accusantium pariatur atque nihil. Beatae maiores optio ea fugiat numquam.	articles/7/2/2013/unde-modi-et	sport	
nam rerum dolorum	Est repudiandae et ad. Libero dolor voluptatem et. Fugit recusandae voluptas ut architecto. Veritatis expedita omnis assumenda provident voluptas deleniti consectetur.	articles/7/2/2013/nam-rerum-dolorum	Sports	rails, jquery
sit atque deserunt	Perspiciatis eligendi voluptas ea. Hic officia quia earum omnis autem. Eum a reiciendis sed. Harum distinctio est sed exercitationem accusantium cupiditate.	articles/7/2/2013/sit-atque-deserunt	HEALTH	
dolor quibusdam ducimus	Repellat nesciunt quia doloremque et rerum. Nesciunt eos nulla sunt asperiores mollitia quidem. Mollitia facilis qui. Ipsam temporibus excepturi rerum non et.	articles/7/2/2013/dolor-quibusdam-ducimus	business	ruby, cloud, jquery
odio recusandae voluptatem	Iusto molestiae expedita delectus rerum. Nostrum reiciendis itaque. Molestiae provident accusantium nemo cupiditate. Qui similique nulla iste deleniti ut omnis.	articles/7/2/2013/odio-recusandae-voluptatem	Sports	medicine, cloud, random-tags
neque libero ut	Soluta ut asperiores rerum. Et facilis et unde explicabo qui non ad. Rerum ut commodi voluptatem recusandae id nemo.	articles/7/2/2013/neque-libero-ut	sport	
perferendis quo enim	Explicabo assumenda exercitationem nihil cumque. Est dicta odit. Mollitia voluptas suscipit qui nemo deserunt.	articles/7/2/2013/perferendis-quo-enim	Business	rails
ad possimus voluptatum	Ea vero quasi rem libero nobis. Consequuntur sequi expedita quis. Possimus deleniti quia.	articles/7/2/2013/ad-possimus-voluptatum	computer world	
eos assumenda iusto	Corrupti iste cupiditate rem vel. Quod esse officia et quisquam sequi necessitatibus. Asperiores odio eius. Numquam id blanditiis quo.	articles/7/2/2013/eos-assumenda-iusto	sport	computer
adipisci quod ratione	Sed consequatur et alias nihil fuga. Fugiat cupiditate sed unde deleniti in quasi. Voluptas qui voluptas.	articles/7/2/2013/adipisci-quod-ratione	Business	random-tags
numquam est quis	Eligendi officia voluptates. Sit unde omnis dolorem. Cum qui dolores. Libero explicabo voluptate ducimus blanditiis magni aut. Rerum omnis explicabo ut fugit quae quasi veritatis.	articles/7/2/2013/numquam-est-quis	business	
debitis alias officia	Molestiae occaecati adipisci enim praesentium. Magni voluptatum sint. Voluptas sit qui in.	articles/7/2/2013/debitis-alias-officia	Business	hate, rails
ut inventore veritatis	Enim sapiente beatae consequatur similique architecto. Quae velit nisi numquam et dolorem. Eos odio dolores dicta adipisci aliquam sed.	articles/7/2/2013/ut-inventore-veritatis	Business	random, music, jquery
ut commodi eos	At vel sequi cumque eius. Perferendis vitae soluta eaque. Atque omnis perferendis eveniet quasi est. Asperiores non ipsam optio.	articles/7/2/2013/ut-commodi-eos	Sports	jquery
placeat eum est	Vel et non nesciunt cumque dolorem. Cumque vero nulla veniam ad non. Recusandae omnis distinctio non itaque. Blanditiis et itaque qui qui nesciunt. Excepturi sit ut.	articles/7/2/2013/placeat-eum-est	Business	
quia expedita sit	Laborum sed vero deleniti quaerat autem a. A accusantium ut adipisci. Rem officia placeat consequatur nostrum sunt iure ipsa.	articles/7/2/2013/quia-expedita-sit	sport	jquery
at ut delectus	Doloribus amet beatae pariatur vel eos. Aut laborum id et eaque reprehenderit ea. Perferendis voluptatem consequatur voluptatum omnis. Accusamus saepe quo.	articles/7/2/2013/at-ut-delectus	business	hate, art, computer
recusandae provident numquam	Molestiae sed tempore consequatur alias ut. Commodi aut voluptas. Aut assumenda debitis qui in fugiat. Harum reprehenderit molestias dolorem.	articles/7/2/2013/recusandae-provident-numquam	Sports	ruby, random
cumque beatae doloribus	Ipsam iure est officia autem eos. Unde provident id. Quia voluptatem velit porro.	articles/7/2/2013/cumque-beatae-doloribus	Business	jquery, music
numquam consequatur non	Non odit sed animi quis. Atque exercitationem minus corporis consectetur itaque sit. Ad adipisci porro reiciendis. Quam deleniti voluptatem et harum quo aliquid.	articles/7/2/2013/numquam-consequatur-non	programming	widget, jquery, tech
quas velit sed	Ut necessitatibus explicabo repellendus possimus eum a voluptate. Voluptatem maxime eaque amet porro accusamus. Optio quaerat officiis blanditiis.	articles/7/2/2013/quas-velit-sed	computer-world	medicine, jquery, widget
enim quia tempora	Reiciendis praesentium nihil. Qui quibusdam ut est. Aliquam iusto ex a. Ut ipsum enim nostrum.	articles/7/2/2013/enim-quia-tempora	Business	
laborum beatae incidunt	Quia doloribus id. Non qui iste. Qui dolorem consectetur. Molestiae commodi laboriosam deleniti consequuntur ut. Minus dolor aliquam quaerat et.	articles/7/2/2013/laborum-beatae-incidunt	Sports	ruby, widget
incidunt voluptates sed	Eum nulla rerum omnis deserunt. Velit asperiores vitae. Voluptatem enim non molestias magni ullam. Accusamus aut esse et est aut. Aut animi fugit excepturi voluptatum.	articles/7/2/2013/incidunt-voluptates-sed	sport	random-tags, cloud
nulla qui minima	Illo molestiae eaque. Minus porro ullam maxime et facere. Magnam et odit. Excepturi vel perferendis nam odit. Aliquam eum quas voluptatem.	articles/7/2/2013/nulla-qui-minima	business	ruby, music
assumenda voluptas quod	Ut explicabo ea nobis maxime ad accusamus. Molestiae magnam minima nostrum. Est deserunt laboriosam.	articles/7/2/2013/assumenda-voluptas-quod	Business	computer
vel architecto non	Ut aliquam eveniet. Similique vero placeat quisquam. Perspiciatis soluta laudantium fugiat doloribus voluptatem. Sit sit totam a odit fugiat non suscipit.	articles/7/2/2013/vel-architecto-non	sport	music
voluptatum qui officiis	Nihil alias magni. Voluptate est odit. Aperiam repellendus non quas consequatur sint fuga. Quam odit est nam autem modi non. Voluptatum omnis aliquid ea animi possimus voluptates.	articles/7/2/2013/voluptatum-qui-officiis	Business	jquery
non dolor quia	Perspiciatis unde id culpa tempore. Soluta velit illo quae magni sint. Totam non et. Soluta est error.	articles/7/2/2013/non-dolor-quia	Business	rails, widget
enim mollitia magni	Non repudiandae sit. In perspiciatis molestiae quia veritatis voluptatum necessitatibus. Quas ipsum delectus.	articles/7/2/2013/enim-mollitia-magni	HEALTH	tech, jquery, art
velit fuga explicabo	Molestiae sed quaerat quae delectus. Sit ut et ad et quis tempora dolorum. Sit qui omnis commodi omnis ut cum vitae.	articles/7/2/2013/velit-fuga-explicabo	business	jquery, ruby, cloud
fugit iste in	Voluptatum rem eum ex voluptas eaque. Est laborum quia officiis beatae rerum. Repellendus iste distinctio in dolorum. Enim sed enim.	articles/7/2/2013/fugit-iste-in	business	
ab aut est	Labore nostrum non excepturi magni consequatur iure. Eos corporis qui. Dignissimos illo quo velit repellat consequatur veritatis.	articles/7/2/2013/ab-aut-est	sport	jquery, medicine, cloud
eveniet deserunt optio	Aut quas ducimus. Quisquam atque quas odit suscipit itaque impedit. Blanditiis quis atque neque delectus beatae aut omnis.	articles/7/2/2013/eveniet-deserunt-optio	computer-world	computer, random-tags
minus adipisci omnis	Incidunt sunt odit recusandae quae quisquam. Qui et in eaque dolorem sint velit. Libero perspiciatis sint velit. Doloribus laborum illo delectus quia. Aut illum qui.	articles/7/2/2013/minus-adipisci-omnis	Business	widget
repellat voluptatem sed	Commodi hic omnis a. Modi quas voluptas commodi enim. Iure nisi ut. Aut quasi quia et voluptatem.	articles/7/2/2013/repellat-voluptatem-sed	programming	love
eos unde laborum	Est illum eos consequatur sed et officiis dolor. Voluptatem nihil est dolore. Et quaerat debitis. Quaerat nostrum quo odio aut ex eos odit. Perferendis delectus aperiam ipsam hic.	articles/7/2/2013/eos-unde-laborum	sport	widget, jquery, tech
consequatur nam voluptates	Quo dolores dolor. Voluptatibus reprehenderit nisi voluptas aspernatur. Autem consequatur corrupti neque voluptas quis omnis quisquam. Autem commodi illo et numquam. Velit molestiae omnis autem officia sunt ipsa.	articles/7/2/2013/consequatur-nam-voluptates	computer-world	
qui laudantium culpa	Deleniti voluptatem sint laboriosam odit et. Harum architecto blanditiis porro quas amet. Dolor eveniet voluptate reprehenderit. Dolores modi error.	articles/7/2/2013/qui-laudantium-culpa	HEALTH	music, random, ruby
incidunt quod omnis	Eum quo non sunt commodi. Blanditiis quia id tenetur quaerat dolores porro. Enim voluptatibus possimus.	articles/7/2/2013/incidunt-quod-omnis	Sports	computer, tech, cloud
delectus praesentium quod	Iure iusto qui doloremque necessitatibus nobis commodi. Aperiam tempore voluptas veritatis quibusdam in beatae. Magni libero fugiat. Iste repudiandae itaque quo.	articles/7/2/2013/delectus-praesentium-quod	programming	cloud, music
vel excepturi quia	Aut quibusdam ea qui unde eveniet neque. Repellat consectetur assumenda fuga cupiditate libero et aspernatur. Voluptatibus repudiandae eveniet quisquam molestiae.	articles/7/2/2013/vel-excepturi-quia	computer world	
et nobis dignissimos	Aspernatur laborum minima delectus nam laboriosam asperiores alias. Ex non et a earum hic sit veniam. Voluptatem optio voluptas accusamus quia. Cum ut error veniam dolores. Libero sit quidem earum sed quaerat est.	articles/7/2/2013/et-nobis-dignissimos	computer world	jquery, widget, cloud
